name: GitHub Feed

on:
  schedule:
    - cron: '10 05 * * *' # 6pm IST
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_GITHUB_READER_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_GITHUB_FEEDER_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update GitHub Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/pharoah/notion-feeder-final/main/dist/index.js?token=GHSAT0AAAAAACMXTDT7LE5A4SWNPXFVPBSIZNA4RMQ
          node index.js
